#!/usr/bin/env bash
# xfarm one-shot installer. Designed to be run two ways:
#
#   curl -fsSL https://raw.githubusercontent.com/mfucek/xfarm/main/install.sh | bash
#   ./install.sh                    # from a local clone
#
# It clones (or pulls) the repo into ~/.xfarm/app, runs preflight (bun,
# Playwright Chromium, optional terminal-notifier), drops an `xfarm` shim
# into ~/.local/bin, and on macOS builds the dockable /Applications/XFarm.app.
#
# Re-running is safe — clones become git-pulls, the shim is rewritten, the
# .app is rebuilt. Set XFARM_NO_APP=1 to skip the .app step.

set -euo pipefail

REPO_URL="https://github.com/mfucek/xfarm.git"
APP_DIR="$HOME/.xfarm/app"
SHIM_DIR="$HOME/.local/bin"
SHIM_PATH="$SHIM_DIR/xfarm"

if [ -t 1 ]; then
  G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; B=$'\033[1m'; D=$'\033[2m'; X=$'\033[0m'
else
  G=""; Y=""; R=""; B=""; D=""; X=""
fi
say()  { printf "%s>%s %s\n" "$G" "$X" "$*"; }
warn() { printf "%s!%s %s\n" "$Y" "$X" "$*"; }
err()  { printf "%sx%s %s\n" "$R" "$X" "$*" >&2; }

# ---- 1. git ----
if ! command -v git >/dev/null 2>&1; then
  err "git not found. Install Xcode Command Line Tools (xcode-select --install) or your package manager's git, then re-run."
  exit 1
fi

# ---- 2. clone or update ----
mkdir -p "$(dirname "$APP_DIR")"
if [ -d "$APP_DIR/.git" ]; then
  say "Updating existing install at $APP_DIR"
  git -C "$APP_DIR" fetch --quiet origin
  # Refuse to clobber local edits — let the user resolve.
  if ! git -C "$APP_DIR" diff --quiet || ! git -C "$APP_DIR" diff --cached --quiet; then
    warn "Local changes in $APP_DIR — skipping pull. Commit/stash them or rm -rf the dir and re-run."
  else
    git -C "$APP_DIR" merge --ff-only origin/HEAD >/dev/null 2>&1 || \
      git -C "$APP_DIR" merge --ff-only origin/main >/dev/null 2>&1 || \
      warn "Couldn't fast-forward. Working tree may be on a non-main branch — leaving it alone."
  fi
elif [ -e "$APP_DIR" ]; then
  err "$APP_DIR exists but isn't a git checkout. Move it aside and re-run."
  exit 1
else
  say "Cloning xfarm → $APP_DIR"
  git clone --quiet "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"

# ---- 3. preflight (bun, playwright, terminal-notifier) ----
# preflight.sh is non-interactive-safe: ask_yes auto-confirms when stdin
# isn't a TTY, which is exactly the curl|bash case.
say "Running preflight checks"
./scripts/preflight.sh

# ---- 4. shim ----
# ~/.local/bin is the XDG-ish convention used by pipx, cargo install, etc.
# Avoids sudo. We warn if it's not on PATH.
mkdir -p "$SHIM_DIR"
cat > "$SHIM_PATH" <<SHIM
#!/bin/sh
# xfarm launcher. Generated by install.sh — edit at your own risk.
APP="$APP_DIR"
cd "\$APP" || { echo "xfarm install not found at \$APP — re-run install.sh" >&2; exit 1; }
# Make sure bun is on PATH for shells that haven't sourced ~/.bun/bin yet.
for d in "\$HOME/.bun/bin" "/opt/homebrew/bin" "/usr/local/bin"; do
  case ":\$PATH:" in *":\$d:"*) ;; *) [ -d "\$d" ] && PATH="\$d:\$PATH" ;; esac
done
export PATH
if [ \$# -eq 0 ]; then
  exec bun src/cli.ts watch
fi
exec bun src/cli.ts "\$@"
SHIM
chmod +x "$SHIM_PATH"
say "Installed shim → $SHIM_PATH"

case ":$PATH:" in
  *":$SHIM_DIR:"*) ;;
  *)
    warn "$SHIM_DIR is not on your PATH."
    printf "  Add this line to your shell rc (~/.zshrc or ~/.bashrc) and reopen the terminal:\n"
    printf "    %sexport PATH=\"\$HOME/.local/bin:\$PATH\"%s\n" "$B" "$X"
    ;;
esac

# ---- 5. dockable .app (macOS only, opt-out via XFARM_NO_APP=1) ----
if [ "$(uname)" = "Darwin" ] && [ "${XFARM_NO_APP:-0}" != "1" ]; then
  say "Building /Applications/XFarm.app"
  ./scripts/install-app.sh || warn ".app build failed — you can retry later with ./scripts/install-app.sh"
fi

cat <<EOF

${G}${B}xfarm installed.${X}

${B}1. Launch${X}
${D}   xfarm                # boots the TUI${X}
${D}   open -a XFarm        # macOS dock launch${X}

${B}2. Configure${X}
${D}   The Config tab opens automatically until cookies + LLM are set up.${X}

${B}3. Update later${X}
${D}   curl -fsSL https://raw.githubusercontent.com/mfucek/xfarm/main/install.sh | bash${X}
${D}   (or: git -C $APP_DIR pull)${X}

EOF
